services:
  frontend:
    image: ghcr.io/valzet/film-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_dist:/usr/share/nginx/html
    networks:
      - film-network

  backend:
    image: ghcr.io/valzet/film-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      PORT: "3000"
      DATABASE_DRIVER: postgres
      DATABASE_URL: postgresql://postgres:5432/${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_MONGODB_URL: mongodb://localhost:27017/practicum
    networks:
      - film-network

  nginx:
    image: ghcr.io/valzet/film-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html
    networks:
      - film-network

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/test/prac.init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./backend/test/prac.films.sql:/docker-entrypoint-initdb.d/02-films.sql:ro
      - ./backend/test/prac.shedules.sql:/docker-entrypoint-initdb.d/03-schedules.sql:ro
    networks:
      - film-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - film-network

volumes:
  frontend_dist:
  postgres_data:
  pgadmin_data:

networks:
  film-network:
